### ISSUE TITLE
lz4 command line utility sub-project for Visual Studio 2022 missing

### ISSUE THREAD

**Issue by hnakayam** [lz4/lz4#1232]
I don't know why, but lz4 command line utility sub-project for Visual Studio 2022 missing.

**Describe the bug**
There's no lz4 directory under build/VS2022 directory. Then opening build/VS2022/lz4.sln from VS2022 IDE will report error "The project file could not be loaded. Could not find a part of the path 'D:\GitHub\lz4\build\VS2022\lz4\lz4.vcxproj" 

**Expected behavior**
lz4 sub-project must be present.

**To Reproduce**
Just open build/VS2022/lz4.sln project from inside Visual Studio 2022 IDE.

**System (please complete the following information):**
 - OS: Windows 10 version 22H2 x64
 - Build System; Visual Studio 2022 version 17.5.5

**Comment by t-mat** [comment]
Hi @hnakayam , thank you for the information.
There're some issues as you pointed out.  They are caused by [my commit](https://github.com/lz4/lz4/commit/b8c4120aa1d335c01877a81a9bf741d18bb72172).  So I should fix them.

I'll write some notes in this issue for the record.  I'm sorry if it'll be bothering you.

**Comment by t-mat** [comment]
## How to reproduce the issue

```bat
: New blank Windows Terminal

cmd.exe /c ver
: Microsoft Windows [Version 10.0.22621.1702]

pushd "%USERPROFILE%\Documents"
git clone https://github.com/lz4/lz4.git

cd lz4
git branch -v
: * dev 9efa7e6 Merge pull request #1230 from lz4/notravis

cmd.exe /c start .\build\VS2022\lz4.sln
```

In my environment, VS2022 opens the `.sln` file without issue.

But after closing the project, `git diff` reports the following diffs.  Note that in the middle of the diff, `lz4\lz4.vcxproj` is removed.  Actually, we don't have `lz4/` directory under [`lz4/build/VS2022/`](https://github.com/lz4/lz4/tree/9efa7e66c8e987e4cbb626f6d60dcb61a4eb0753/build/VS2022)

```
diff --git a/build/VS2022/lz4.sln b/build/VS2022/lz4.sln
index 6a2779f..2d397d7 100644
--- a/build/VS2022/lz4.sln
+++ b/build/VS2022/lz4.sln
@@ -1,6 +1,6 @@
 Microsoft Visual Studio Solution File, Format Version 12.00
-# Visual Studio 15
-VisualStudioVersion = 15.0.28307.271
+# Visual Studio Version 17
+VisualStudioVersion = 17.6.33712.159
 MinimumVisualStudioVersion = 10.0.40219.1
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "liblz4-dll", "liblz4-dll\liblz4-dll.vcxproj", "{9800039D-4AAA-43A4-BB78-FEF6F4836927}"
 EndProject
@@ -19,8 +19,6 @@ Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "fullbench-dll", "fullbench-
                {9800039D-4AAA-43A4-BB78-FEF6F4836927} = {9800039D-4AAA-43A4-BB78-FEF6F4836927}
        EndProjectSection
 EndProject
-Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "lz4", "lz4\lz4.vcxproj", "{60A3115E-B988-41EE-8815-F4D4F253D866}"
-EndProject
 Global
        GlobalSection(SolutionConfigurationPlatforms) = preSolution
                Debug|Win32 = Debug|Win32
@@ -85,14 +83,6 @@ Global
                {13992FD2-077E-4954-B065-A428198201A9}.Release|Win32.Build.0 = Release|Win32
                {13992FD2-077E-4954-B065-A428198201A9}.Release|x64.ActiveCfg = Release|x64
                {13992FD2-077E-4954-B065-A428198201A9}.Release|x64.Build.0 = Release|x64
-               {60A3115E-B988-41EE-8815-F4D4F253D866}.Debug|Win32.ActiveCfg = Debug|Win32
-               {60A3115E-B988-41EE-8815-F4D4F253D866}.Debug|Win32.Build.0 = Debug|Win32
-               {60A3115E-B988-41EE-8815-F4D4F253D866}.Debug|x64.ActiveCfg = Debug|x64
-               {60A3115E-B988-41EE-8815-F4D4F253D866}.Debug|x64.Build.0 = Debug|x64
-               {60A3115E-B988-41EE-8815-F4D4F253D866}.Release|Win32.ActiveCfg = Release|Win32
-               {60A3115E-B988-41EE-8815-F4D4F253D866}.Release|Win32.Build.0 = Release|Win32
-               {60A3115E-B988-41EE-8815-F4D4F253D866}.Release|x64.ActiveCfg = Release|x64
-               {60A3115E-B988-41EE-8815-F4D4F253D866}.Release|x64.Build.0 = Release|x64
        EndGlobalSection
        GlobalSection(SolutionProperties) = preSolution
                HideSolutionNode = FALSE
```

Therefore, I think (my) VS2022 silently fix some issue(s).

## TODOs

- [x] Create PR to fix this issue.
  - [x] Copy from `lz4/build/VS2017/lz4/` to `lz4/build/VS2022/lz4/`
  - [x] Update entire project with genuine VS2022
  - [x] Provide batch build script to prevent same issue.
  - [x] Add test entry to `.github/workflows/ci.yml`.
- [ ] Think about other (meta) build system such as `cmake`, `meson`, etc.

**Comment by t-mat** [comment]
As for missing `build/VS2022/lz4/`.  Since I missed to follow 2c392c5f, this directory had been removed from my commit.
I'll add the following lines to `build/.gitignore` which may automatically (un)ignore

```
# Ignore binaries
VS*/bin/

# Include VS????/lz4/ projects
!VS*/lz4
```

**Comment by hnakayam** [comment]
Hey all, I have confirmed that the lz4 subproject builds fine with VS2022. Thanks!
